name: Build

#  This workflow is the Provider's CI build that will run on every commit for the provider codebase

on:
  push:
  workflow_dispatch:

env:
  PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
  PACT_BROKER_URL: ${{ secrets.PACT_BROKER_URL }}
  PACT_BROKER_PUBLISH_VERIFICATION_RESULTS: true
  GIT_COMMIT: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4.2.2
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'

      - name: Run tests
        run: make test record_deployment can_i_deploy